add usedRukMaiChaiDuangDaoTeePrawSang
narze/react-useless pull request #105
Opened 2022-10-05 17:26 UTC by nonkung51

- added usedRukMaiChaiDuangDaoTeePrawSang

this hook just added `รักไม่ใช่ดวงดาวที่พราวแสง` after any input

2022-10-05 17:50 UTC, narze requested changes
Looking good, but it should be `use`RukMaiChaiDuangDaoTeePrawSang instead of `used`RukMaiChaiDuangDaoTeePrawSang, could you change them?

2022-10-06 02:54 UTC, nonkung51 commented
Sure! Really sorry i changed it already na krub

2022-10-06 03:14 UTC, narze commented on src/hooks-usage/useRukMaiChaiDuangDaoTeePrawSang.tsx
> +        code: 'const value = usedRukMaiChaiDuangDaoTeePrawSang("จาวา ไม่ใช่ จาวาสคริปต์")',
```suggestion
        code: 'const value = useRukMaiChaiDuangDaoTeePrawSang("จาวา ไม่ใช่ จาวาสคริปต์")',
```

2022-10-06 03:14 UTC, narze reviewed
👍🏻

2022-10-06 03:15 UTC, merged