add useChanochaBigBrainCells
narze/react-useless pull request #120
Opened 2022-10-07 13:44 UTC by nonkung51

- added useChanochaBigBrainCells return number of Chan-O-Cha big brain cells

ref: https://www.youtube.com/watch?v=lgJfHVwZ_F8

2022-10-07 14:11 UTC, Leomotors requested changes

2022-10-07 14:11 UTC, leomotors commented on src/hooks-usage/useChanochaBigBrainCells.tsx
> +      },
I think we don't need this section, duplicate example

```suggestion
```

2022-10-08 04:28 UTC, nonkung51 commented on src/hooks-usage/useChanochaBigBrainCells.tsx
> +      },
fixed krub 😃

2022-10-08 07:37 UTC, Leomotors approved these changes
![](https://media.tenor.com/QaGZ50VlEPEAAAAd/think-about-it-use-your-brain.gif)

2022-10-08 07:38 UTC, Leomotors commented on src/hooks/useChanochaBigBrainCells.ts
> +  return 84000 * 1000000
ลุงเขาบอกว่า 840,000 ล้านอ่ะครับ ไม่ฝากแก้ครับ เดี๋ยวผมแก้เอง 555

```suggestion
  return 840000 * 1000000
```

2022-10-08 07:41 UTC, merged

2022-10-08 08:16 UTC, nonkung51 commented on src/hooks/useChanochaBigBrainCells.ts
> +  return 84000 * 1000000
แง้ ขอบคุณครับ 555