Create useDoubleEffect.ts
narze/react-useless pull request #71
Opened 2022-10-02 16:17 UTC by minnyww

2022-10-02 16:24 UTC, narze requested changes
That's so useless 😂 
By the way please create usage component that use this hook (See readme)

2022-10-02 16:33 UTC, minnyww commented
> 

alrady done

2022-10-03 05:22 UTC, narze commented on src/hooks-usage/useDoubleEffect.tsx
> +          "Hi react"
```suggestion
          console.log("Hi react")
```

2022-10-03 05:24 UTC, narze approved these changes
nice
nice

2022-10-03 05:24 UTC, merged