Add useLeft
narze/react-useless pull request #72
Opened 2022-10-02 16:22 UTC by minnyww

2022-10-02 16:24 UTC, narze requested changes
Please add usage component that use this hook.
Also please remove extra lines

2022-10-02 16:46 UTC, minnyww commented
> Please add usage component that use this hook. Also please remove extra lines

already done

2022-10-03 05:23 UTC, narze requested changes
Please remove yarn lockfile

2022-10-06 16:22 UTC, narze commented
😪

2022-10-07 22:11 UTC, merged